apiVersion: v2
name: basic-demo
description: A Helm chart for Kubernetes

type: application


version: 1.0.0

appVersion: "1.0.0"

dependencies:
- name: ingress-nginx
  version:  4.8.1
  repository: https://kubernetes.github.io/ingress-nginx